- hosts: utility.example.com
  user: ansible-user
  become: true
  vars_files:
    # Contains variables to connect to the Manager
    - engine_vars.yml
    # Contains encrypted engine_password variable using ansible-vault
    - passwords.yml
  tasks:
    - name: Create NFS Directories for DEV Environemnt
      file:
        path: /VM_Export/DEV_NFS/{{ item }}
        state: directory
        mode: 0755
        owner: vdsm
        group: kvm
      loop:
        - data
        - export
        - iso

    - name: Copy Export Configuration File
      copy:
        src: ./Resources/DEV_exports
        dest: /etc/exports

    - name: Export Filesystem
      shell: |
        exportfs -a
