---
- hosts: rhv-m.example.com
  user: ansible-user
  become: true
  vars_files:
    # Contains variables to connect to the Manager
    - engine_vars.yml
    # Contains encrypted engine_password variable using ansible-vault
    - passwords.yml

  pre_tasks:
    - name: Login to RHV
      ovirt_auth:
        url: "{{ engine_url }}"
        username: "{{ engine_user }}"
        password: "{{ engine_password }}"
        ca_file: "{{ engine_cafile | default(omit) }}"
        insecure: "{{ engine_insecure | default(true) }}"
      tags:
        - always

  vars:
    data_center_name: Development
    cluster_name: Development_Cluster
    cluster_description: Development Cluster

  tasks:
    - name: Get Network Facts
      ovirt_network_facts:
        auth: "{{ ovirt_auth }}"
        pattern: name=Development_Workstations_Net*
    - debug:
        var: ovirt_networks

    - name: Setup Network Facts
      set_fact:
        net_id: "{{ ovirt_networks | map(attribute='id') | list }}"

    - name: Output of Network ID
      debug:
         var: net_id

    - name: Set Template Network
      ovirt_template:
        auth: "{{ ovirt_auth }}"
        state: present
        cluster: "{{ cluster_name }}"
        storage_domain: Dev_iSCSI_Data
        name: Dev_WS_VM_Template
        vnic_profile_mappings:
          - source_network_name: Development_Servers_Net
            source_profile_name: Development_Servers_Net
            target_profile_id: "{{ net_id }}"

  post_tasks:
    - name: Logout from RHV
      ovirt_auth:
        state: absent
        ovirt_auth: "{{ ovirt_auth }}"
      tags:
        - alwaysovi
