---
- hosts: rhv-m.example.com
  user: ansible-user
  become: true
  vars_files:
    # Contains variables to connect to the Manager
    - engine_vars.yml
    # Contains encrypted engine_password variable using ansible-vault
    - passwords.yml

  pre_tasks:
    - name: Login to RHV
      ovirt_auth:
        url: "{{ engine_url }}"
        username: "{{ engine_user }}"
        password: "{{ engine_password }}"
        ca_file: "{{ engine_cafile | default(omit) }}"
        insecure: "{{ engine_insecure | default(true) }}"
      tags:
        - always

  vars:
    data_center_name: Development
    cluster_name: Development_Cluster
    cluster_description: Develeopment Cluster
    # host_name: rhel-h-1
    # host_fqdn_name: rhel-h-1.example.com

  tasks:

    - name: Configure Power Management RHEL-H-2
      ovirt_host_pm:
        auth: "{{ ovirt_auth }}"
        name: rhel-h-2
        address: 192.2.2.227
        options:
          lanplus=true
        username: admin
        password: redhat
        type: ipmilan
        order: 1

    - name: Configure Power Management RHV-H-2
      ovirt_host_pm:
        auth: "{{ ovirt_auth }}"
        name: rhv-h-2
        address: 192.2.2.224
        options:
          lanplus=true
        username: admin
        password: redhat
        type: ipmilan
        order: 1



  post_tasks:
    - name: Logout from RHV
      ovirt_auth:
        state: absent
        ovirt_auth: "{{ ovirt_auth }}"
      tags:
        - alwaysovi
