---
- hosts: rhv-m.example.com
  user: ansible-user
  become: true
  vars_files:
    # Contains variables to connect to the Manager
    - engine_vars.yml
    # Contains encrypted engine_password variable using ansible-vault
    - passwords.yml  
  tasks:
    - name: Run ovirt-engine config
      command: engine-config -s SpiceProxyDefault=http://utility.example.com:3128

    - name: Restart ovirt-engine Service
      systemd:
        name: ovirt-engine
        state: restarted
