---
- hosts: utility.example.com
  user: ansible-user
  become: true
  vars_files:
    # Contains variables to connect to the Manager
    - engine_vars.yml
    # Contains encrypted engine_password variable using ansible-vault
    - passwords.yml  
  tasks:
    - name: Configure firewalld
      firewalld:
        port: 3128/tcp
        permanent: yes
        immediate: yes
        state: enabled
    - name: Install SQUID Service
      yum:
        name: squid
        state: latest
    - name: Copy SQUID Configuration File
      copy:
        src: ./Resources/squid.conf
        dest: /etc/squid/squid.conf
    - name: Start and Enable SQUID Service
      systemd:
        name: squid
        enabled: yes
        state: started
